language: node_js
node_js:
  - "8"
install:
  - yarn
script:
  - yarn run build
after_success:
  - yarn run build
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git status
  - git add README.md
  - git status
  - git commit -m "Automatic update of README.md"
  - git status
  - git push --quiet https://$GITHUB_AUTH_TOKEN@github.com/mohebifar/made-in-iran master
